title: Bo Yin's Homepage
page-top-title: Bo Yin
top-section-bg-text: Computer Science & Internet of Things
home-subtitle: Bo Yin&ensp;|&ensp;尹博
copyright-text: '&copy; Bo Yin 2025. All Rights Reserved.'
